server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.249.131
    username: ego
    password: ego
    virtual-host: /ego
ego:
  sms:
    accessKeyId: LTAI7GS3oLcUcUi9
    accessKeySecret: WWVhOk9UhvbrnF0XdFwEviTMMepz8U
